### ISSUE TITLE
Issues with protein family comparison recipe

### ISSUE THREAD

**Issue by ajvenkat** [getcontacts/getcontacts#48]
Hi,

I am trying to perform a comparison of a few protein structures belonging to the same family using the instructions provided at this link: https://getcontacts.github.io/family_flare.html

I have run into a few issues:
- First, the usage in the example at the above link and the usage in the current distribution of getcontacts are different.
Online documentation:
`get_resilabels.py --input_file match.xml --output_prefix labels_`

Code usage: 
```
get_resilabels.py [-h] --ssm_filename SSM_FILENAME
                         [--output_dir OUTPUT_DIR]
                         [--include_loconf INCLUDE_LOCONF]
```

- Second, the xml parsing appears to fail:
```
$get_resilabels.py --ssm_filename match_v1.xml --output_dir ./
Parsing SSM file match_v1.xml
Traceback (most recent call last):
  File "/home/venkaaj1/softwares/getcontacts/get_resilabels.py", line 183, in <module>
    main()
  File "/home/venkaaj1/softwares/getcontacts/get_resilabels.py", line 176, in main
    pdbs = extract_pdbs(input_filelines)
  File "/home/venkaaj1/softwares/getcontacts/get_resilabels.py", line 144, in extract_pdbs
    pdb = fileline.split()[2].upper()[:4]
IndexError: list index out of range
```

I am unable to share the input xml file that is throwing this error.

Thanks for your help.

**Comment by frederikkem** [comment]
I'm having the same issue. I think maybe you shouldn't download the XML file from PDBefold but the Text output (which has a similar format as described in the get_resilabels.py) and does run: 
`Parsing SSM file output_ssm.dat
Writing ./XXX_labels.tsv`
This, however, results in empty label files for me.

**Comment by RasmusFonseca** [comment]
@agchempa any update yet?

**Comment by frederikkem** [comment]
I have already tried including the `--include_loconf` flag. Still empty files (I also have plenty of high-confidence alignments so it shouldn't affect it anyways). 
Everything else in the protocol has worked! But it is a little hard to clearly see in the flareplot without the labels simplified.

**Comment by agchempa** [comment]
It sounds like it might be a parsing bug then. The output format from SSM is unfriendly to parsing, so I would not be surprised if this were the case. Can I take a look at it over the weekend and get back to you?

**Comment by saikat0003** [comment]
Hi,
I am getting the following error while using the get_resilabels.py:
[]
False
Traceback (most recent call last):
  File "/home/saikat/softwares/getcontacts/get_resilabels.py", line 210, in <module>
    main()
  File "/home/saikat/softwares/getcontacts/get_resilabels.py", line 196, in main
    aligned_residues = parse_more_than_two_queries(
  File "/home/saikat/softwares/getcontacts/get_resilabels.py", line 136, in parse_more_than_two_queries
    resname = resname[:5] + ":" + str(int(resname[5:])) if resname else ""
ValueError: invalid literal for int() with base 10: '.pdb'

I am using the following command:
get_resilabels.py --input_gesamt match.txt --output_path ./ --proteins rgs01 rgs02 rgs04 rgs08 rgs09 rgs10 rgs16

Could you please fix the issue?

**Comment by saikat0003** [comment]
Hi, 
I am using the following command:
get_resilabels.py --input_gesamt match.txt --output_path ./ --proteins rgs01 rgs02 rgs04 rgs08 rgs09 rgs10 rgs16

It shows the following error:
Traceback (most recent call last):
  File "/home/saikat/softwares/getcontacts/get_resilabels.py", line 210, in <module>
    main()
  File "/home/saikat/softwares/getcontacts/get_resilabels.py", line 196, in main
    aligned_residues = parse_more_than_two_queries(
  File "/home/saikat/softwares/getcontacts/get_resilabels.py", line 136, in parse_more_than_two_queries
    resname = resname[:5] + ":" + str(int(resname[5:])) if resname else ""
ValueError: invalid literal for int() with base 10: '.pdb'

Could you please fix the issue? Thank you.
