### ISSUE TITLE
Add the option to output distance

### ISSUE THREAD

**Issue by yongwangCPH** [getcontacts/getcontacts#49]
I am using 
get_static_contacts.py --structure protein.pdb --output output.tsv --itypes all
to generate the contact list. 
# total_frames:1 beg:0 end:0 stride:1 interaction_types:sb,pc,ps,ts,vdw,hb,lhb 
# Columns: frame, interaction_type, atom_1, atom_2[, atom_3[, atom_4]] 
0 sb A:ASP:94:OD1 A:HIS:127:NE2 

But I also need the information of distance for each atom pair. It would be nice to output the distance in the last column, something like:
0 sb A:ASP:94:OD1 A:HIS:127:NE2 **3.4**

Could you add an option so as the users can choose to output the distance info? For example like:
get_static_contacts.py --structure protein.pdb --output output.tsv --itypes all **--outdist yes**

(I posted the requirement here after a few emails exchanging with @RasmusFonseca)

Thanks!
Yong

**Comment by yongwangCPH** [comment]
Thanks, Rasmus. 
I tried the updated version, but got errors:

Traceback (most recent call last):
  File "/Users/yongwang/Work/software/getcontacts/get_dynamic_contacts.py", line 76, in <module>
    from contact_calc.compute_contacts import *
  File "/Users/yongwang/Work/software/getcontacts/contact_calc/compute_contacts.py", line 38, in <module>
    from .hydrophobics import compute_hydrophobics
ModuleNotFoundError: No module named 'contact_calc.hydrophobics'

I didn't have this problem for the original version, do you have any idea on what happened?

Yong

**Comment by yongwangCPH** [comment]
@RasmusFonseca 
Sorry, I just noticed that the issue has been closed. So not sure if you can still see it.

**Comment by RasmusFonseca** [comment]
I can still see it. Will check it out tonight.

**Comment by yongwangCPH** [comment]
@RasmusFonseca 
The issue was gone when I made a clean version of getcontacts by deleting the old version and installing the latest one. Thanks a lot anyway!
