### ISSUE TITLE
Installation not working out of box

### ISSUE THREAD

**Issue by cgseitz** [getcontacts/getcontacts#71]
Hello,

I am trying to install get contacts, but the installation does not work on my workstation. Here are the steps I am taking:

```
conda install -c conda-forge vmd-python
conda install tk=8.6 numpy scipy expat matplotlib scikit-learn pytest pandas seaborn cython
git clone https://github.com/davidhallac/TICC.git #doing this since I don't have pip access
conda install -c https://conda.anaconda.org/rbetz vmd-python
git clone https://github.com/getcontacts/getcontacts.git
echo "export PATH=`pwd`/getcontacts:\$PATH" >> ~/.bashrc
source ~/.bashrc
get_static_contacts.py --structure 4irp.pdb --itypes hb --output contacts_1.tsv
```
and I get this error:
```
cseitz@canoes:/net/gpfs-amarolab/cseitz/from_jam/projects/vedran/3_docking/IFD/analysis$ get_static_contacts.py --structure 4irp.pdb --itypes hb --output contacts_1.tsv
Traceback (most recent call last):
  File "/net/gpfs-amarolab/cseitz/from_jam/projects/vedran/3_docking/IFD/analysis/getcontacts/get_static_contacts.py", line 19, in <module>
    from contact_calc.compute_contacts import *
  File "/net/gpfs-amarolab/cseitz/from_jam/projects/vedran/3_docking/IFD/analysis/getcontacts/contact_calc/compute_contacts.py", line 25, in <module>
    except ModuleNotFoundError:
NameError: name 'ModuleNotFoundError' is not defined
```
Do you know what I need to change about my installation? Thanks!

**Comment by RasmusFonseca** [comment]
Hi! 

I suspect this is a python versioning issue (ModuleNotFound is from 3.5 forward). Any chance you could try this with a python 3.6 environment? E.g. 
```
conda create -n myenv python=3.6
```
 before you run the commands above

**Comment by cgseitz** [comment]
Hi Rasmus,

Sorry for the delay. My previous conda environment (above) was python 3.9. When I create a conda environment using python 3.6, I get this error:

```
(py36) cseitz@canoes:/net/gpfs-amarolab/cseitz/from_jam/projects/vedran/3_docking/IFD/analysis/getcontacts$ get_static_contacts.py --structure 4irp.pdb --itypes hb --output contacts_1.tsv
Traceback (most recent call last):
  File "/net/gpfs-amarolab/cseitz/from_jam/projects/vedran/3_docking/IFD/analysis/getcontacts/get_static_contacts.py", line 93, in <module>
    main()
  File "/net/gpfs-amarolab/cseitz/from_jam/projects/vedran/3_docking/IFD/analysis/getcontacts/get_static_contacts.py", line 80, in main
    ligand, solv, lipid, sele1, sele2)
  File "/net/gpfs-amarolab/cseitz/from_jam/projects/vedran/3_docking/IFD/analysis/getcontacts/contact_calc/compute_contacts.py", line 226, in compute_contacts
    index_to_atom = gen_index_to_atom(top, traj)
  File "/net/gpfs-amarolab/cseitz/from_jam/projects/vedran/3_docking/IFD/analysis/getcontacts/contact_calc/contact_utils.py", line 234, in gen_index_to_atom
    trajid = load_traj(top, traj, 0, 1, 1)
  File "/net/gpfs-amarolab/cseitz/from_jam/projects/vedran/3_docking/IFD/analysis/getcontacts/contact_calc/contact_utils.py", line 105, in load_traj
    trajid = molecule.load(top_file_type, top)
RuntimeError: Unable to load structure file '4irp.pdb' format 'pdb'
```

**Comment by RasmusFonseca** [comment]
I didn't know ModuleNotFound was dropped in 3.9 .. thanks! 

Does that PDB file load in regular vmd? I suspect there's some formatting issue as it's recognized the extension.
