### ISSUE TITLE
Cannot Allocate Memory

### ISSUE THREAD

**Issue by Dan-Burns** [getcontacts/getcontacts#84]
Hello,
I've had no trouble running getdynamiccontacts in a bash for loop on a cluster environment with linux (fedora or redhat or something).

Now I'm trying to run it locally on ubuntu and I get weird behavior. The first time I ran it, it made it through the first iteration before erroring out.  Now it won't make it through even the first iteration.

```
Traceback (most recent call last):
  File "~/python_packages/getcontacts/get_dynamic_contacts.py", line 97, in <module>
    main()
  File "~/python_packages/getcontacts/get_dynamic_contacts.py", line 80, in main
    compute_contacts(top, traj, output, itypes, geom_criteria, cores, beg, end, stride, distout,
  File "~/python_packages/getcontacts/contact_calc/compute_contacts.py", line 281, in compute_contacts
    w.start()
  File "~/anaconda3/envs/getcontacts/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "~/anaconda3/envs/getcontacts/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "~/anaconda3/envs/getcontacts/lib/python3.9/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "~/anaconda3/envs/getcontacts/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "~/anaconda3/envs/getcontacts/lib/python3.9/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

```
I'm using 10 of the 12 available cores:

```
for i in $(seq 0 29)
do

                                 get_dynamic_contacts.py \
                                 --topology protein.pdb \
                                 --trajectory simulation_$i.xtc \
                                 --output contacts_$i.tsv \
                                 --cores 10 \
                                 --itypes all --distout
done

```

Thank you,
Dan

**Comment by Dan-Burns** [comment]
I have a 12th gen I7 with 8 performance cores and 4 efficient cores apparently. Using 8 cores doesn't throw any error.
