### ISSUE TITLE
execution error

### ISSUE THREAD

**Issue by saikat0003** [getcontacts/getcontacts#90]
Hi,
I am trying to install getcontact. I am getting following error:
ImportError: /home/sp1564/.conda/envs/vmd-python/lib/python3.9/site-packages/vmd/../../../libnetcdf.so.19: undefined symbol: H5Pset_fapl_ros3
Could you please suggest me how to resolve the issue?

**Comment by RasmusFonseca** [comment]
That one is unfamiliar to me. My first guess would be a newer incompatible version of netcdf. I'm not getting any search hits on `set_fapl` though. If possible could you try a lower version of python maybe (3.8 or 3.6)

**Comment by jodypacalon** [comment]
Same problem here. Using a lower version of Python doesn't seems to do the trick.

**Comment by andrefaure** [comment]
I am having exactly the same problem when running on linux with python 3.6. Any idea what's going on? I installed all dependencies indicated in the readme in a dedicated env with conda.

I also get the same error when I open an interactive python session and import vmd:
```
>>> import vmd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/users/blehner/afaure/conda/envs/getcontacts/lib/python3.6/site-packages/vmd/__init__.py", line 25, in <module>
    vmd = imp.load_dynamic(__name__, vmdlib)
  File "/users/blehner/afaure/conda/envs/getcontacts/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /users/blehner/afaure/conda/envs/getcontacts/lib/python3.6/site-packages/vmd/../../../libnetcdf.so.19: undefined symbol: H5Pset_fapl_ros3
```

**Comment by andrefaure** [comment]
I managed to run getcontacts after downgrading libnetcdf from v4.8 to v4.7.

But now the installation test results in 1728 lines of interactions in the `5xnd_hbonds.tsv` file rather than 1874 as indicated in the readme. Does this mean I still don't have a working installation?

>$get_dynamic_contacts.py --topology 5xnd_topology.pdb --trajectory 5xnd_trajectory.dcd --itypes hb --output 5xnd_hbonds.tsv
> wkf_thread_set_self_cpuaffinitylist: sched_setaffinity: Invalid argument
> wkf_thread_set_self_cpuaffinitylist: sched_setaffinity: Invalid argument
> wkf_thread_set_self_cpuaffinitylist: sched_setaffinity: Invalid argument
> wkf_thread_set_self_cpuaffinitylist: sched_setaffinity: Invalid argument
> wkf_thread_set_self_cpuaffinitylist: sched_setaffinity: Invalid argument
> wkf_thread_set_self_cpuaffinitylist: sched_setaffinity: Invalid argument
> wkf_thread_set_self_cpuaffinitylist: sched_setaffinity: Invalid argument
> wkf_thread_set_self_cpuaffinitylist: sched_setaffinity: Invalid argument
> wkf_thread_set_self_cpuaffinitylist: sched_setaffinity: Invalid argument
> wkf_thread_set_self_cpuaffinitylist: sched_setaffinity: Invalid argument
> wkf_thread_set_self_cpuaffinitylist: sched_setaffinity: Invalid argument
> wkf_thread_set_self_cpuaffinitylist: sched_setaffinity: Invalid argument
> wkf_thread_set_self_cpuaffinitylist: sched_setaffinity: Invalid argument
> wkf_thread_set_self_cpuaffinitylist: sched_setaffinity: Invalid argument
> wkf_thread_set_self_cpuaffinitylist: sched_setaffinity: Invalid argument
> Detected no solvent atoms (specify manually using --solv)
> Detected no lipid atoms (specify manually using --lipid)
> Detected 2 ligand atoms (resnames: CA)
> Warning: No ligand atoms are in --sele or --sele2
> Processing 5xnd_trajectory.dcd (frame 0 to 19 with stride of 1) as 1 fragments
> 
> Finished computing contacts for fragment 0: 20 frames from 0 to 19 in strides of 1 taking 0.092869 s
> 
> Total computation time: 0.294916 seconds
> topology=5xnd_topology.pdb
> trajectory=5xnd_trajectory.dcd
> output=5xnd_hbonds.tsv
> cores=6
> solv=
> sele=protein
> sele2=protein
> stride=1

>$ wc -l 5xnd_hbonds.tsv
> 1730 5xnd_hbonds.tsv
