### ISSUE TITLE
Running the testing script gives this error: TypeError: cannot pickle '_io.TextIOWrapper' object

### ISSUE THREAD

**Issue by hachen94** [getcontacts/getcontacts#96]
Hi all, I have macbook M2 pro, and I downloaded and installed everything following the instruction. Running 'get_dynamic_contacts.py' alone gives no error, but running the 'get_dynamic_contacts.py --topology 5xnd_topology.pdb \
                        --trajectory 5xnd_trajectory.dcd \
                        --itypes hb \
                        --output 5xnd_hbonds.tsv' 
give this picking error as below. Does anyone know how to solve this? Thanks!

(vmd-python) hachen@001T303828 5xnd % get_dynamic_contacts.py --topology 5xnd_topology.pdb \
                        --trajectory 5xnd_trajectory.dcd \
                        --itypes hb \
                        --output 5xnd_hbonds.tsv
Detected no solvent atoms (specify manually using --solv)
Detected no lipid atoms (specify manually using --lipid)
Detected 2 ligand atoms (resnames: CA)
Warning: No ligand atoms are in --sele or --sele2
Processing 5xnd_trajectory.dcd (frame 0 to 19 with stride of 1) as 1 fragments

Traceback (most recent call last):
  File "/Users/hachen/getcontacts/get_dynamic_contacts.py", line 97, in <module>
    main()
  File "/Users/hachen/getcontacts/get_dynamic_contacts.py", line 80, in main
    compute_contacts(top, traj, output, itypes, geom_criteria, cores, beg, end, stride, distout,
  File "/Users/hachen/getcontacts/contact_calc/compute_contacts.py", line 286, in compute_contacts
    consumer.start()
  File "/Users/hachen/anaconda3/envs/vmd-python/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/hachen/anaconda3/envs/vmd-python/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/hachen/anaconda3/envs/vmd-python/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/hachen/anaconda3/envs/vmd-python/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/hachen/anaconda3/envs/vmd-python/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/hachen/anaconda3/envs/vmd-python/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/hachen/anaconda3/envs/vmd-python/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_io.TextIOWrapper' object
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/hachen/anaconda3/envs/vmd-python/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
  File "/Users/hachen/anaconda3/envs/vmd-python/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
  File "/Users/hachen/anaconda3/envs/vmd-python/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
  File "/Users/hachen/anaconda3/envs/vmd-python/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
  File "/Users/hachen/anaconda3/envs/vmd-python/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
  File "/Users/hachen/anaconda3/envs/vmd-python/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
    exitcode = _main(fd, parent_sentinel)
  File "/Users/hachen/anaconda3/envs/vmd-python/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    exitcode = _main(fd, parent_sentinel)
    exitcode = _main(fd, parent_sentinel)
  File "/Users/hachen/anaconda3/envs/vmd-python/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
  File "/Users/hachen/anaconda3/envs/vmd-python/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/hachen/anaconda3/envs/vmd-python/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/hachen/anaconda3/envs/vmd-python/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
  File "/Users/hachen/anaconda3/envs/vmd-python/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "/Users/hachen/anaconda3/envs/vmd-python/lib/python3.9/multiprocessing/synchronize.py", line 110, in __setstate__
    self = reduction.pickle.load(from_parent)
  File "/Users/hachen/anaconda3/envs/vmd-python/lib/python3.9/multiprocessing/synchronize.py", line 110, in __setstate__
    self = reduction.pickle.load(from_parent)
    self = reduction.pickle.load(from_parent)
  File "/Users/hachen/anaconda3/envs/vmd-python/lib/python3.9/multiprocessing/synchronize.py", line 110, in __setstate__
    self = reduction.pickle.load(from_parent)
  File "/Users/hachen/anaconda3/envs/vmd-python/lib/python3.9/multiprocessing/synchronize.py", line 110, in __setstate__
  File "/Users/hachen/anaconda3/envs/vmd-python/lib/python3.9/multiprocessing/synchronize.py", line 110, in __setstate__
    self = reduction.pickle.load(from_parent)
  File "/Users/hachen/anaconda3/envs/vmd-python/lib/python3.9/multiprocessing/synchronize.py", line 110, in __setstate__
    self._semlock = _multiprocessing.SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory
    self._semlock = _multiprocessing.SemLock._rebuild(*state)
    self._semlock = _multiprocessing.SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory
    self._semlock = _multiprocessing.SemLock._rebuild(*state)
    self._semlock = _multiprocessing.SemLock._rebuild(*state)
    self._semlock = _multiprocessing.SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory
FileNotFoundError: [Errno 2] No such file or directory
FileNotFoundError: [Errno 2] No such file or directory
FileNotFoundError: [Errno 2] No such file or directory

**Comment by batuujin** [comment]
Hi, I ran into the same problem, 
Did you happen to solve this problem by chance?

**Comment by skblnw** [comment]
The error was due to problem with multiprocessing. A temporary workaround is to specify **-cores 1**. 
I am testing with Mac M1, not sure whether this is related.
